Feature/105 server connect setting
PLUB2022/Plub-Android pull request #10
Opened 2022-11-16 11:49 UTC by koownij

## Presentation layer
Presentation layer의 경우 확인할 필요가 없습니다! (경석님이 작업하신 부분, 추후 104번 브랜치에서 코드 리뷰할 예정)

## App, Data, Domain layer
주의깊게 봐주시길 바랍니다. 
특히 http status code가 401인 경우 자동으로 토큰 갱신 후 401이 내려온 api를 재호출하는 로직이 있습니다.

아래 코드와 주석을 참고해주세요
```kotlin
// 토큰 자동 갱신 로직을 사용하지 않을 경우 @NormalRetrofit 사용 - NormalNetworkModule에서 Api 의존성 주입
// 토큰 자동 갱신 로직을 사용할 경우 @AuthRetrofit 사용 - AuthNetworkModule에서 Api 의존성 주입
    @Singleton
    @Provides
    fun providePlubJwtTokenApi(@NormalRetrofit retrofit: Retrofit): PlubJwtTokenApi {
        return retrofit.create(PlubJwtTokenApi::class.java)
    }
```

## 주의가 필요한 파일
AuthenticationInterceptor.kt
NormalNetworkModule.kt
TokenAuthenticator.kt

## Conflict 다수 발생 및 기존 경석님이 작업하신 코드 제거
develop branch merge 하는 과정에서 conflict가 많이 발생했으며 기존에 경석님이 Sample로 Server와 통신한 코드를 제거했습니다. 해당 작업 중에 문제가 생겼을 수도 있으니 주의 부탁드립니다 ... !

2022-11-17 09:39 UTC, BehappyEveryone requested changes

2022-11-17 09:39 UTC, BehappyEveryone commented on app/build.gradle.kts
> +    implementation("com.squareup.retrofit2:adapter-rxjava2:2.3.0")
Libraries 사용 해주세요

2022-11-17 09:39 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/AuthenticationInterceptor.kt
> +            runBlocking {
runBlocking을 쓰는건 좀 많이 위험할 것 같은데 accessToken을 못받아오면 쭉 블락상태인데 예외처리가 따로 필요하거나 혹은 다른 방법을 사용해야할 것 같아요

2022-11-17 09:39 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +        val access = runBlocking {
위 코멘트와 동일합니다

2022-11-17 09:39 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +        val refresh = runBlocking {
위 코멘트와 동일합니다

2022-11-17 09:39 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +            val newAccess = runBlocking {
위 코멘트와 동일합니다

2022-11-17 09:39 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +                    runBlocking {
위 코멘트와 동일합니다

2022-11-17 09:39 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +            runBlocking {
위 코멘트와 동일합니다

2022-11-17 09:39 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +                plubJwtTokenRepository.saveAccessTokenAndRefreshToken(tokenResponse.body()!!.data.accessToken, tokenResponse.body()!!.data.refreshToken)
null safe 써주세요 body가 비어있으면 그대로 죽습니다

2022-11-17 09:39 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +                        "Bearer " + runBlocking { plubJwtTokenRepository.getRefreshToken() }
위 코멘트와 동일합니다

2022-11-17 09:39 UTC, BehappyEveryone commented on data/build.gradle.kts
> +    implementation("com.squareup.retrofit2:adapter-rxjava2:2.3.0")
Dependencies 써주세요

2022-11-17 09:39 UTC, BehappyEveryone commented on data/src/main/java/com/plub/data/model/PlubJwtTokenResponse.kt
> +    val data : PlubJwtTokenData
response 데이터는 옵셔널하게 만들어주세요 해당 키의 값을 못받으면 null로 받고 non null로 참조되면 그대로 죽습니다

2022-11-17 09:39 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/home/InterestRegisterAdapter.kt
> +class InterestRegisterAdapter(private var mlist : List<String>) : RecyclerView.Adapter<InterestRegisterAdapter.ViewHolder?>() {
ListAdapter로 diffutil 써주세요

2022-11-17 09:39 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/home/InterestRegisterAdapter.kt
> +    inner class ViewHolder( itemView: View) : RecyclerView.ViewHolder(itemView) {
뷰홀더는 재활용을 위해 따로 만들어주시고 뷰바인딩 써주세요

2022-11-17 09:39 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/home/MainCategoryAdapter.kt
> +class MainCategoryAdapter : RecyclerView.Adapter<MainCategoryAdapter.ViewHolder?>() {
위 코멘트와 동일합니다

2022-11-17 09:39 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/home/MainFragment.kt
> +    lateinit var mainCategoryAdapter: MainCategoryAdapter
LoginFragment 기준으로 다시 만들어주세요

2022-11-17 09:39 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/home/MainInterestRegisterFragment.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
위와 동일합니다

2022-11-17 09:39 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/home/MainRecommendMeetXAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
위와 동일합니다

2022-11-17 09:39 UTC, BehappyEveryone commented on presentation/src/main/res/layout/fragment_interests_register.xml
> +        android:textColor="#000000"
리소스 하드코딩 하지말아주세요

2022-11-18 01:05 UTC, koownij commented on app/build.gradle.kts
> +    implementation("com.squareup.retrofit2:adapter-rxjava2:2.3.0")
아 이거 못봤는데 필요 없어보여서 그냥 제거하는게 좋을 것 같아요

2022-11-24 21:55 UTC, BehappyEveryone requested changes

2022-11-24 21:55 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +        val access = plubJwtTokenRepository.getAccessToken()
기존 제 코드에서 io 코루틴 쓰레드로 변환하는 코드를 제거한 이유가 무엇인가요?

2022-11-24 21:55 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +        val newAccess = plubJwtTokenRepository.getAccessToken()
위와 동일

2022-11-24 21:55 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +        val refresh = plubJwtTokenRepository.getRefreshToken()
위와 동일

2022-11-24 21:55 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +            val tokenResponse = plubJwtTokenApi.reIssueToken(JWTTokenReIssueRequest(refresh))
왜 레파지토리 없이 api에서 바로 접근하셨나요?

2022-11-24 21:55 UTC, BehappyEveryone commented on data/src/main/java/com/plub/data/model/PlubJwtTokenResponse.kt
> +)
ApiResponse 사용해주세요

2022-11-24 21:55 UTC, BehappyEveryone commented on data/src/main/java/com/plub/data/repository/PlubJwtTokenRepositoryImpl.kt
> +    ) }.first().accessToken
fist 연산자를 쓴 이유는 무엇인가요?

2022-11-25 00:20 UTC, koownij commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +            val tokenResponse = plubJwtTokenApi.reIssueToken(JWTTokenReIssueRequest(refresh))
1.
app 모듈의 경우 data 모듈 의존성을 가지고 있어 api에 바로 접근할 수 있었습니다. 

2.
Repository의 경우 DataSource의 출처를 모르게하여 추후 DataSource를 변경하더라도 (예를 들면 Realm에서 Room으로) 동일한 Interface로 데이터를 요청할 수 있기 때문에 사용한다고 알고 있어요. 

만약 여러개의 파일에서 api에서 바로 접근한다고 가정해보겠습니다.
api가 변경된다면 api를 사용한 ***모든 파일***을 수정해야하는 단점이 있습니다. 이를 해결하기 위해 Repository 패턴을 사용한다고 알고있어요. (Repository를 사용하면 api, RepositoryImpl 부분만 수정하면 되기 때문)

단, plubJwtTokenApi의 경우 TokenAuthenticator.kt 단 한 곳에서만 사용되므로 굳이 Repository를 사용할 이유가 없다고 생각했습니다. (여러 파일에서 사용되는 다른 api와는 달리 plubJwtTokenApi는 변경된 경우 TokenAuthenticator.kt만 수정하면 되기 때문)

2022-11-25 00:24 UTC, koownij commented on data/src/main/java/com/plub/data/model/PlubJwtTokenResponse.kt
> +)
DataDto를 말씀하시는 걸까요?

2022-11-25 00:29 UTC, koownij commented on data/src/main/java/com/plub/data/repository/PlubJwtTokenRepositoryImpl.kt
> +    ) }.first().accessToken
DataStore의 경우 flow를 반환합니다.

collect를 사용하면 값이 바뀔 때마다 emit되지만 ac token, re token의 경우 단 한번만 값을 받아오면 되므로 first를 사용했어요

2022-11-25 00:30 UTC, koownij commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +        val access = plubJwtTokenRepository.getAccessToken()
DataStore 역시 자동으로 io 쓰레드에서 작업하기 때문입니다.

2022-11-25 01:00 UTC, BehappyEveryone commented on app/src/main/java/com/plub/plubandroid/di/TokenAuthenticator.kt
> +            val tokenResponse = plubJwtTokenApi.reIssueToken(JWTTokenReIssueRequest(refresh))
객체지향 원칙에 따라 해당 api는 추상화 시켜주는 것이 좋다고 봅니다
말씀하신 내용이라면 한 곳에서만 쓰이는 모든 api는 굳이 레파지토리를 만들 필요가 없어져요

2022-11-27 03:54 UTC, BehappyEveryone approved these changes

2022-11-27 03:55 UTC, merged