Feature/120 create gathering
PLUB2022/Plub-Android pull request #13
Opened 2023-01-21 10:24 UTC by koownij

2023-01-21 20:03 UTC, BehappyEveryone requested changes

2023-01-21 20:03 UTC, YeonjunNotFR commented on data/src/main/java/com/plub/data/dto/account/MyInfoResponse.kt
> +data class MyInfoResponse(
response 값은 옵셔널하게 넣어주는게 좋아요
null 일 경우에 서버에서 안내려주기로 했는데
안내려주는 경우에 해당 프로퍼티에 접근하면 NPE 로 죽을 위험이 있어요
ex) val email: String = ""

2023-01-21 20:03 UTC, YeonjunNotFR commented on data/src/main/java/com/plub/data/dto/account/MyInfoResponse.kt
> +    val profileImage: String?
서버에서 null은 안내려주기로 약속되어 있으니 non-null로 수정 부탁드려요

2023-01-21 20:03 UTC, YeonjunNotFR commented on data/src/main/java/com/plub/data/util/Constants.kt
> +const val KAKAO_REST_API_KEY = "cf10cf6916173ccffcd5d8e2c0fa5622"
키 값 나중에 개발 끝나고나서 한번 전체 갱신 받아야할 것 같아요 ㅋㅋㅋㅋ 갱신하기 쉽게 키값만 한 곳에 모아둘까요?
도메인에 놔두면 레이어 관계없이 쓸 수 있을 것 같은데

2023-01-21 20:03 UTC, YeonjunNotFR commented on domain/src/main/java/com/plub/domain/model/vo/account/MyInfoResponseVo.kt
> +    val profileImage: String? = null
위 DTO와 마찬가지로 non-null로 수정 부탁해요

2023-01-21 20:03 UTC, YeonjunNotFR commented on domain/src/main/java/com/plub/domain/usecase/PostReIssueTokenUseCase.kt
> +            if(index == 1) {
상수는 const val로 변경해주세요

2023-01-21 20:03 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/createGathering/dayAndOnOfflineAndLocation/CreateGatheringDayAndTimeAndOnOfflineAndLocationFragment.kt
> +                if (viewModel.uiState.value != CreateGatheringDayAndTimeAndOnOfflineAndLocationPageState())
해당 코드와 같이 판별을 위한 비지니스 로직은 가능한한 viewmodel에 넣는게 좋을 것 같아요
밑에 is로 타입 체크 로직도 마찬가지로
viewModel.initUiState(it) 로 발생한 이벤트는 무조건 뷰모델로 넘겨주되 뷰모델 함수에서 판별을 하는

2023-01-21 20:03 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/createGathering/dayAndOnOfflineAndLocation/CreateGatheringDayAndTimeAndOnOfflineAndLocationFragment.kt
> +            requireActivity().supportFragmentManager,
fragment에선 parentFragmentManager 사용하시면 돼요

2023-01-21 20:03 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/createGathering/dayAndOnOfflineAndLocation/bottomSheet/BottomSheetSearchLocationViewModel.kt
> +    private val _hideKeyboard = MutableSharedFlow<Unit>(0, 1, BufferOverflow.DROP_OLDEST)
BaseViewModel이면 eventFlow 사용 가능해요!

2023-01-21 20:03 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/createGathering/dayAndOnOfflineAndLocation/bottomSheet/BottomSheetSearchLocation.kt
> +        binding.lifecycleOwner = this
fragment에선 this보다 viewLifecycleOwner 사용해주세요 버그 생겨요

2023-01-21 20:03 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/createGathering/dayAndOnOfflineAndLocation/bottomSheet/adapter/KakaoLocationRecyclerViewAdapter.kt
> +    inner class KakaoLocationViewHolder(val binding: LayoutRecyclerKakaoLocationByKeywordBinding) :
뷰홀더는 재사용 할 수 있도록 inner class보다 아예 파일을 빼서 클래스 만들어주면 더 좋을 것 같아요

2023-01-21 20:03 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/createGathering/peopleNumber/CreateGatheringPeopleNumberViewModel.kt
> +    val updateSeekbarProgressAndPositionX: (progress: Int, position: Float) -> Unit  = { progress, position ->
이건 미사용 코드인가요?

2023-01-21 20:03 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/createGathering/question/adapter/QuestionViewHolder.kt
> +            binding.imageViewDelete.setOnClickListener {
리스너나 초기화 코드는 init 함수에서 사용해주세요

2023-01-21 20:03 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/createGathering/question/bottomSheet/BottomSheetDeleteQuestion.kt
> +        binding.position = position
BottomSheetDialogFragment라도 결국 본질은 fragment에요
fragment 생명 주기에 따라 동작을 시켜주는게 좋아요
ex) SelectMenuBottomSheetDialog

2023-01-21 20:03 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/util/Extensions.kt
> +fun EditText.afterTextChanged(method: (editable: Editable?) -> Unit) {
이 함수 이미 xml에 기본적으로 제공되어 있던데 다른건가요?

2023-01-21 20:03 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/util/TimeFormatter.kt
> +            "오후 ${hour - 12}시 ${min}분"
이건 dateFormat 같은거 쓰는게 좋을 것 같아요 한글로 고정으로 박아버리면 타 언어 사용자들은 이해 못하니까
dateFormat은 locale 로 언어 변환해주거든요
그리고 하드코딩 금지

2023-01-22 11:06 UTC, koownij commented on data/src/main/java/com/plub/data/util/Constants.kt
> +const val KAKAO_REST_API_KEY = "cf10cf6916173ccffcd5d8e2c0fa5622"
보통 BuildConfig에서 관리하더라구요 ㅋㅋ

2023-01-22 11:20 UTC, koownij commented on presentation/src/main/java/com/plub/presentation/ui/createGathering/peopleNumber/CreateGatheringPeopleNumberViewModel.kt
> +    val updateSeekbarProgressAndPositionX: (progress: Int, position: Float) -> Unit  = { progress, position ->
음 아뇨!
fragment_create_gathering_people_number.xml의 seekbar에 data binding 되어있습니다!

2023-01-22 13:33 UTC, koownij commented on presentation/src/main/java/com/plub/presentation/util/Extensions.kt
> +fun EditText.afterTextChanged(method: (editable: Editable?) -> Unit) {
xml이 아닌 BindingAdapter.kt 또는 Activity/Fragment.kt 에서 사용하기 위해 만들었습니다!

2023-01-22 14:28 UTC, koownij commented on presentation/src/main/java/com/plub/presentation/util/TimeFormatter.kt
> +            "오후 ${hour - 12}시 ${min}분"
dateFormat 관련해서 찾아본 결과
AM/PM -> 오전/오후 까지는 locale에 따라 자동으로 변경되나, 시/분/초 같은 경우는 안되는 것 같습니다

2023-01-23 17:23 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/createGathering/selectPlubCategory/CreateGatheringSelectPlubCategoryFragment.kt
> +                if (viewModel.uiState.value != CreateGatheringSelectPlubCategoryPageState())
미적용

2023-01-23 17:24 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/createGathering/selectPlubCategory/CreateGatheringSelectPlubCategoryViewModel.kt
> +    private val maxCategoryCount = 5
companion object {
   private const val CATEGORY_MAX_COUNT = 5
}

2023-01-24 05:17 UTC, BehappyEveryone approved these changes

2023-01-24 05:17 UTC, merged