Feature/104 plubing home layout
PLUB2022/Plub-Android pull request #15
Opened 2023-01-22 15:47 UTC by rudtjr1106

2023-01-23 16:08 UTC, koownij requested changes

2023-01-23 16:08 UTC, lluke0 commented on app/src/main/java/com/plub/plubandroid/di/UseCaseModule.kt
> +    fun providesTestPostHomeUseCase(repository: HomePostRepository): TestPostHomeUseCase {
테스트용 코드 삭제 가능할까요?

2023-01-23 16:08 UTC, lluke0 commented on data/src/main/java/com/plub/data/api/BrowseApi.kt
> +    suspend fun browseRecommendationGathering(
browse -> fetch로 변경 부탁드려요!
네이밍 컨벤션 확인 부탁드립니다

2023-01-23 16:08 UTC, lluke0 commented on data/src/main/java/com/plub/data/api/BrowseApi.kt
> +    @GET("/api/plubbings/categories/{categoryId}")
data/api/Endpoints.kt 사용 부탁드립니닷

2023-01-23 16:08 UTC, lluke0 commented on data/src/main/java/com/plub/data/api/PostHomeApi.kt
> +interface PostHomeApi {
테스트용 api 제거 부탁드려요

2023-01-23 16:08 UTC, lluke0 commented on data/src/main/java/com/plub/data/dto/plubJwt/SampleHomePostResponse.kt
> +    val authCode : String?
non-null로 변경 부탁드립니다 추가로 기본 값 설정두요!
`val authCode : String=""`

2023-01-23 16:08 UTC, lluke0 commented on data/src/main/java/com/plub/data/dto/plubJwt/applicantsrecruit/ApplicantsRecruitResponse.kt
> +data class ApplicantsRecruitResponse(
Response의 경우 기본 값 설정 부탁드립니다
val plubbingId = -1

2023-01-23 16:08 UTC, lluke0 commented on data/src/main/java/com/plub/data/dto/plubJwt/recommendationgatheringdata/RecommendationGatheringData.kt
> +package com.plub.data.dto.plubJwt.recommendationgatheringdata
package 이동 부탁드릴게요!
plubJwt package안에는 jwt 관련 파일만 있어야합니다

2023-01-23 16:08 UTC, lluke0 commented on data/src/main/java/com/plub/data/mapper/recruitdetailmapper/RecruitDetailResponseMapper.kt
> +                title,
title = this.title 이런 식으로 수정 가능할까요?
data class에 변수가 추가되거나 순서가 바뀌면 유지보수하기 어려울 것 같습니다

2023-01-23 16:08 UTC, lluke0 commented on data/src/main/java/com/plub/data/repository/ApplicantsRecruitReposImpl.kt
> +class ApplicantsRecruitReposImpl @Inject constructor(private val recruitApi: RecruitApi) : ApplicantsRecruitRepository, BaseRepository() {
Repos -> Repository 풀네임으로 부탁드릴게요! (네이밍 컨벤션)

2023-01-23 16:08 UTC, lluke0 commented on data/src/main/java/com/plub/data/repository/HostRecruitReposImpl.kt
> +class HostRecruitReposImpl @Inject constructor(private val recruitApi: RecruitApi) : HostRecruitRepository, BaseRepository() {
Repos -> Repositroy

2023-01-23 16:08 UTC, lluke0 commented on data/src/main/java/com/plub/data/repository/ReplyApplicantsRecruitReposImpl.kt
> +        TODO("Not yet implemented")
TODO 지워주세요

2023-01-23 16:08 UTC, lluke0 commented on domain/src/main/java/com/plub/domain/model/vo/home/GatheringItemVo.kt
> +    val img_res : String,
카멜케이스로 수정 부탁드립니다

2023-01-23 16:08 UTC, lluke0 commented on domain/src/main/java/com/plub/domain/model/vo/home/recommendationgatheringvo/RecommendationGatheringDataPageableResponseVo.kt
> +    val sort: RecommendationGatheringDataSortResponseVo,
Sort 전용 Vo가 있는 이유가 있을까요?

2023-01-23 16:08 UTC, lluke0 commented on domain/src/main/java/com/plub/domain/model/vo/home/recommendationgatheringvo/RecommendationGatheringDataResponseVo.kt
> +    //val pageable : RecommendationGatheringDataPageable,
주석 지워주세요

2023-01-23 16:08 UTC, lluke0 commented on domain/src/main/java/com/plub/domain/repository/HomePostRepository.kt
> +    suspend fun trySampleData(request: HomePostRequestVo) : Flow<UiState<HomePostResponseVo>>
Sample 관련 코드 지워주세욧

2023-01-23 16:08 UTC, lluke0 commented on domain/src/main/java/com/plub/domain/usecase/HostRecruitUseCase.kt
> +class HostRecruitUseCase @Inject constructor(private val hostRecruitRepository: HostRecruitRepository
UseCase의 경우 클래스의 이름만 보고 어떤 기능을 수행하는지 명확하게 파악할 수 있어야합니다. 
아래 코드를 보면 endRecruit, seeApplicants 두 가지 동작을 수행하는데 한 가지 동작만 수행하도록 분리해주시고 클래스 네이밍도 변경 부탁드릴게요

2023-01-23 16:08 UTC, lluke0 commented on domain/src/main/java/com/plub/domain/usecase/InterestUseCase.kt
> +class InterestUseCase @Inject constructor(
UseCase 이름만 보고도 어떤 동작을 수행하는지 알 수 있게끔 수정 부탁드립니다!
InterestUseCase만 보고서는 관심사를 등록하는 UseCase인지 알 수 없어요

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/state/CategoryChoiceState.kt
> +    val listOrGrid : Boolean = false
listOrGrid로 네이밍을 한 경우 true이면 list이고 false이면 Grid인지 변수 이름만 보고 정확하게 판단하기 어렵습니다.
차라리 isListShape로 이름을 바꾸는게 더 좋을 듯 싶습니다. 더 좋은 방법은 enum class를 생성하는게 어떨까 ... 싶어요

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/categoryChoice/CategoryChoiceFragment.kt
> +                        Log.d("최하단", "최하단")
Log대신 PlubLogger 사용해주세요.
PlubLogger 사용 시 , 릴리즈 모드에서 Log 값이 노출되지 않습니다

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/categoryChoice/CategoryChoiceViewModel.kt
> +    private val _backMainPage =
event 적용 부탁드립니다

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/categoryChoice/CategoryChoiceViewModel.kt
> +    val backMainPage: SharedFlow<Unit> =
backMainPage 보다는 goToMainPage가 더 가독성이 좋을 것 같아요

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/categoryChoice/CategoryChoiceViewModel.kt
> +            categoriesGatheringUseCase.invoke(CategoriesGatheringRequestVo(categoryId, 0)).collect{ state->
categoriesGatheringUseCase(CategoriesGatheringRequestVo(categoryId, 0)) invoke 생략 가능합니다. 생략해주세요

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/categoryChoice/CategoryChoiceViewModel.kt
> +                state.successOrNull()?.let { _recommendationData.emit(it) }
inspectUiState 사용 부탁드립니다. SignUpViewModel 참고

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/categoryChoice/CategoryChoiceViewModel.kt
> +        //TODO 그리드로 변경
주석 제거해주세요

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/categoryChoice/viewholder/MainRecommendGridViewHolder.kt
> +            textViewPeople.text = "모집 인원 ${item.curAccountNum + item.remainAccountNum}명"
하드 코딩 금지

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/main/MainFragment.kt
> +                        0 -> HasNotDataRecycler()
음 해당 로직 viewModel로 빼면 어떨까요?

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/main/MainFragment.kt
> +        val mConcatAdapter = ConcatAdapter()
HasNotDataRecycler와 중복되는 코드가 많네요

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/main/adapter/MainCategoryAdapter.kt
> +            is MainCategoryParentViewHoler -> holder.bind(currentList[position])
분기가 하나밖에 없는데 is를 사용한 이유가 있으신가요?

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/main/adapter/MainCategoryItemAdapter.kt
> +    override fun areItemsTheSame(oldItem: CategoriesDataResponseVo, newItem: CategoriesDataResponseVo): Boolean = oldItem == newItem
모든 diffUtil의 값을 oldItem == newItem으로 하신 이유가 따로 있을까요?

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/main/viewholer/MainCategoryParentViewHoler.kt
> +            layoutManager = GridLayoutManager(context, 4)
`4` const val로 변경부탁드립니다

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/main/viewholer/MainRecommendListViewHolder.kt
> +    private var bookmarkFlag = false
bookmarkFlag보다는 isBookmarked가 더 좋을 것 같아요

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/recruitment/ApplyPlubbingFragment.kt
> +    fun getAnswerList() : List<ApplicantsRecruitAnswerListVo>{
혹시 어떤 동작을 수행하는 함수인지 알 수 있을까요?

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/recruitment/RecruitmentFragment.kt
> +                viewModel
이 부분 코드 설명 가능할까요?

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/recruitment/RecruitmentFragment.kt
> +    fun returnFragmentArgs(): String {
return -> get
return 하나만 사용하게끔 수정 부탁드립니다

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/recruitment/RecruitmentFragment.kt
> +    fun initDetailPage(data: RecruitDetailResponseVo) {
아래 부분 전부 databinding + PageState 적용 부탁드릴게요

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/recruitment/adapter/DetailRecruitProfileAdapter.kt
> +                if (position < 8){
position이 8보다 작은 경우에만 bind 시키는 이유가 있을까요?

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/recruitment/adapter/QuestionsViewHolder.kt
> +        const val SPACE = ". "
string.xml에서 사용하면 될 듯 싶습니다

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/recruitment/adapter/QuestionsViewHolder.kt
> +            textViewQuestion.text = number.toString() + SPACE + item.question
string.xml에서 사용하면 될 듯 싶습니다

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/recruitment/hostrecruitment/HostRecruitmentFragment.kt
> +    fun initDetailPage(data: RecruitDetailResponseVo) {
아래 내용 전부 databinding + pageState 적용 부탁드려요

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/res/layout/fragment_category_choice.xml
> +                    android:text="인기순"
하드 코딩 금지

2023-01-23 16:08 UTC, lluke0 commented on presentation/src/main/res/layout/fragment_apply_plubbing.xml
> +        <androidx.core.widget.NestedScrollView
NestedScrollView를 사용한 이유가 있을까요?
이걸 사용해버리면 recyclerview를 사용하는 이유가 없어져서 ...

2023-01-23 17:32 UTC, BehappyEveryone commented on data/src/main/java/com/plub/data/mapper/CategoryListDataResponseMapper.kt
> +        }!!
!! 다 제거 부탁드립니다

2023-01-23 17:38 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/home/plubing/categoryChoice/CategoryChoiceFragment.kt
> +    fun setListRecycler() {
왜 private이 아닌 public이죠?

2023-01-24 10:03 UTC, rudtjr1106 commented on presentation/src/main/res/layout/fragment_apply_plubbing.xml
> +        <androidx.core.widget.NestedScrollView
> NestedScrollView를 사용한 이유가 있을까요?
> 이걸 사용해버리면 recyclerview를 사용하는 이유가 없어져서 ...

Figma 디자인에 위 타이틀 글씨인 취미모임 관심사 등록~~~~ 이 부분또한 스크롤이 가능해서
따로 viewholder를 만들어 recycler에 추가하는 것 대신 위처럼 스크롤뷰를 사용했습니다!
타이틀용 viewholder를 제작해서 위로 붙이는게 더 좋을까요???

2023-01-28 13:38 UTC, closed without merging