Feature/104 plubbing homelayout recreate
PLUB2022/Plub-Android pull request #26
Opened 2023-02-24 00:17 UTC by rudtjr1106

2023-03-06 06:31 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/plubhome/adapter/HomeAdapter.kt
> +class HomeAdapter(private val listener: HomeDelegate) : ListAdapter<HomePlubListVo, RecyclerView.ViewHolder>(
수정된 코드

2023-03-06 06:32 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/plubhome/viewholder/HomeCategoryParentViewHolder.kt
> +class HomeCategoryParentViewHolder (
수정된 코드

2023-03-06 06:32 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/plubhome/viewholder/HomeCategoryViewHolder.kt
> +class HomeCategoryViewHolder (
수정된 코드

2023-03-06 06:33 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/plubhome/adapter/HomeCategoryAdapter.kt
> +class HomeCategoryAdapter(private val listener: HomeAdapter.HomeDelegate) : ListAdapter<CategoriesDataResponseVo, RecyclerView.ViewHolder>(
수정된 코드

2023-03-07 08:03 UTC, koownij requested changes

2023-03-07 08:03 UTC, lluke0 commented on data/src/main/java/com/plub/data/api/Endpoints.kt
> +        const val GET_BIG_CATEGORIES = "$CATEGORY_URL"
BIG 보다는 PARENT 어떤가요?

2023-03-07 08:03 UTC, lluke0 commented on domain/src/main/java/com/plub/domain/model/vo/home/applicantsRecruitVo/ApplicantsRecruitAnswerListVo.kt
> +data class ApplicantsRecruitAnswerListVo(
List가 들어가서 List형으로 착각할 수도 있을 것 같아요

2023-03-07 08:03 UTC, lluke0 commented on domain/src/main/java/com/plub/domain/model/vo/home/recruitDetailVo/RecruitDetailJoinedAccountsListVo.kt
> +data class RecruitDetailJoinedAccountsListVo(
List가 들어가서 List형이라고 착각할 수 있을 것 같아요

2023-03-07 08:03 UTC, lluke0 commented on domain/src/main/java/com/plub/domain/usecase/GetCategoriesGatheringUseCase.kt
> +class GetCategoriesGatheringUseCase @Inject constructor(
recommendationGatheringRepository에서 카테고리 값을 가져오는데 ... Recommendation에 관한 Category 목록들을 가져오는 건가요? 만약 그렇다면 네이밍을 GetRecommendationCategoriesGatheringUseCase 으로 바꿔야할 것 같아요. Category를 사용하는 곳이 꽤 많아서 정확하게 적어주는게 좋을 것 같습니다.

2023-03-07 08:03 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/categoryGathering/filter/GatheringFilterFragment.kt
> +                DaysType.ALL -> { checkedDayButton(ALL) }
해당 부분 로직 변경

2023-03-07 08:03 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/recruitment/apply/ApplyPlubbingViewModel.kt
> +    private var answerList : List<ApplicantsRecruitAnswerListVo> = emptyList()
pageState 로 변경하지 않은 이유 체크

2023-03-07 08:03 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/categoryGathering/CategoryGatheringFragment.kt
> +        }
resourceProvider 사용하면 전부 ViewModel로 로직 뺄 수 있을 것 같아

2023-03-07 08:03 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/categoryGathering/filter/GatheringFilterState.kt
> +    val subHobbies : @RawValue List<SubHobbyVo> = emptyList(),
@RawValue는 뭔가요?

2023-03-07 08:03 UTC, koownij commented on presentation/src/main/java/com/plub/presentation/ui/main/home/recruitment/bottomsheet/BottomSheetProfileViewHolder.kt
> +            listener.onProfileClick(accountId)
accountId를 null로 한다음에
accountId?.let{ listener.onProfileClick(it) }
이렇게 하는건 어떨까요?

2023-03-07 12:17 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/recruitment/bottomsheet/BottomSheetProfileViewHolder.kt
> +            listener.onProfileClick(accountId)
```kotlin
private var accountId: Int = 0

    init {
        binding.imageViewProfile.setOnClickListener {
            listener.onProfileClick(accountId)
             }
    }

    fun bind(item: RecruitDetailJoinedAccountsListVo) {
        binding.apply {
            GlideUtil.loadImage(root.context, item.profileImage, imageViewProfile)
            imageViewProfile.clipToOutline = true
            textViewProfileName.text = item.nickname
            accountId = item.accountId
        }
    }
 ```
 
 `bind` 함수가 실행되기 전에 imageViewProfile이 클릭되면 onProfieClick에 accountId값이 0이 들어가게 됨.
 하지만 accountId를 null로 만든 후 `accountId?.let{ listener.onProfileClick(it) }` 다음과 같이 코드를 작성하게 되면
 `bind` 함수가 실행되기 전이라면 `listener.onProfileClick(it)`이 실행되지 않기 때문에 잘못된 메서드 호출을 막을 수 있음

2023-03-07 14:05 UTC, koownij approved these changes

2023-03-07 14:07 UTC, merged