Feature/168 MyPage(마이페이지 홈, 마이페이지 설정, 모집중인 모임, 대기중인 모임), 104번 코드 수정
PLUB2022/Plub-Android pull request #34
Opened 2023-03-14 06:26 UTC by rudtjr1106

2023-03-14 06:35 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/plubhome/HomeFragmentViewModel.kt
> +            val jobCategories : Job = launch {
job 을 이용한 병렬처리 vs 일반 직렬 어떤게 더 좋을까요??

2023-03-14 06:37 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/profile/MyPageFragment.kt
> +                gatheringType: MyPageGatheringMyType,
요거 지금은 안쓰이는데 활동중인 모임에서 사용하기 때문에 제거하지 않겠습니다!

2023-03-14 07:08 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/profile/adapter/MyPageParentGatheringAdapter.kt
> +        fun onClickGathering(gatheringParentType : MyPageGatheringStateType, gatheringType : MyPageGatheringMyType, plubbingId : Int)
위에서 언급한 내용대로 활동중인 모임에서 사용하기 때문에 제거하지 않겠습니다!

2023-03-17 09:13 UTC, BehappyEveryone requested changes

2023-03-17 09:13 UTC, YeonjunNotFR commented on data/src/main/java/com/plub/data/dto/myPage/MyApplicationResponse.kt
> +    val answers : List<AnswersDataResponse>
= emptyList()

2023-03-17 09:13 UTC, YeonjunNotFR commented on data/src/main/java/com/plub/data/api/MyPageApi.kt
> +        @Query("status") status: String
Api 클래스들에서 status key 같은거 다 const val로 뺴줄 수 있어? ex) 게시판 api

2023-03-17 09:13 UTC, YeonjunNotFR commented on data/src/main/java/com/plub/data/dto/recruitdetail/host/AccountDataResponse.kt
>  data class AccountDataResponse(
같은 파일이 두개야 하나 지워줘

2023-03-17 09:13 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/main/home/plubhome/HomeFragmentViewModel.kt
> +            val jobCategories : Job = launch {
난 병렬처리 하는게 더 좋다고 생각해 근데 밑에 getRecommendationGatheringUsecase를 제외시킨 이유가 있어?

2023-03-17 09:13 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/main/home/plubhome/HomeFragmentViewModel.kt
> +    private fun getTitleViewList() : List<HomePlubListVo>{
이렇게 list로 합쳐도 상관없긴 한데
그냥 
add(getHomeTitleView())
add(getHomeCategoryView())
로 해도 돼
편한대로

2023-03-17 09:13 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/main/home/profile/recruiting/RecruitingGatheringViewModel.kt
> +    var plubbingId: Int = 0
이거 필수값이면 Delegates.notNull<Int>()로 해줘

2023-03-17 09:13 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/main/home/profile/recruiting/RecruitingGatheringViewModel.kt
> +    private fun getApplicantsList(list : List<AccountsVo>): List<MyPageDetailVo>{
forEach 말고 map으로 
list.map {
    MyPageDetailVo(viewType = ..., application = it)
}

2023-03-17 09:13 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/main/home/profile/viewHolder/MyPageParentGatheringViewHolder.kt
> +            when(item.gatheringType){
val textRes = when(item.gatheringType) {
    ...
}

textViewGatheringType.text = root.context.getString(textRes)

줄일 수 있는 코드는 다 줄여보자

2023-03-17 09:13 UTC, YeonjunNotFR commented on presentation/src/main/java/com/plub/presentation/ui/main/home/profile/MyPageFragment.kt
> +        binding.apply {
데이터바인딩을 안쓴 이유는?

2023-03-17 09:13 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/main/home/profile/MyPageFragment.kt
> +        binding.apply {
무슨 코드인걸까

2023-03-21 02:27 UTC, closed without merging