Feature/171 plubbing schedule botton sheet
PLUB2022/Plub-Android pull request #35
Opened 2023-03-14 15:05 UTC by koownij

2023-03-17 08:34 UTC, BehappyEveryone requested changes

2023-03-17 08:34 UTC, BehappyEveryone commented on data/src/main/java/com/plub/data/api/ScheduleApi.kt
> +    suspend fun getEntireSchedule(@Path("plubbingId") plubbingId:Int, @Query("cursorId") cursorId:Int): Response<ApiResponse<GetEntireScheduleResponse>>
plubbingId const val 로 빼두면 좋을 것 같아

2023-03-17 08:34 UTC, BehappyEveryone commented on data/src/main/java/com/plub/data/mapper/schedule/EntireScheduleResponseMapper.kt
> +                        ScheduleVo(
ScheduleVo의 맵퍼도 따로 만드는게 서버에 맞춰 유연하게 작업하기 좋아

2023-03-17 08:34 UTC, BehappyEveryone commented on data/src/main/java/com/plub/data/mapper/schedule/EntireScheduleResponseMapper.kt
> +                            calendarAttendList = CalendarAttendListVo(it.calendarAttendList.calendarAttendResponseList.map { calendar ->
얘도

2023-03-17 08:34 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/main/plubing/schedule/PlubingScheduleViewModel.kt
> +        lastContent?.let { prevSchedule ->
groupby, flatmap으로 변경해줘

2023-03-17 08:34 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/main/plubing/schedule/adapter/scheduleCard/PlubingScheduleContentViewHolder.kt
> +        val (color, imageResource) = if (TimeFormatter.getEpochMilliFromyyyyDashmmDashddFormat(
함수가 너무 크고 보기 힘들어

2023-03-17 08:34 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/main/plubing/schedule/adapter/scheduleCard/profileFold/PlubingScheduleProfileFoldAdapter.kt
> +    override fun areItemsTheSame(
왜 항상 false인거야?

2023-03-17 08:34 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/main/plubing/schedule/addOrEdit/PlubingAddOrEditSchedulePageState.kt
> +data class Date(
네이밍을 바꾸는게 좋을 것 같아

2023-03-17 08:34 UTC, BehappyEveryone commented on presentation/src/main/java/com/plub/presentation/ui/main/plubing/schedule/addOrEdit/PlubingAddOrEditSchedulePageState.kt
> +data class Time(
위와 마찬가지로

2023-03-20 06:05 UTC, koownij commented on presentation/src/main/java/com/plub/presentation/ui/main/plubing/schedule/adapter/scheduleCard/profileFold/PlubingScheduleProfileFoldAdapter.kt
> +    override fun areItemsTheSame(
프로필의 경우 서버에서 더미 데이터로 동일한 url string 값을 내려주더라구 
oldItem == newItem으로 하면 동일한 값이 있는 경우에 정상적으로 diffutil이 동작하지 않아서 무조건 갱신되게끔 false로 했어

2023-03-21 07:42 UTC, BehappyEveryone approved these changes

2023-03-21 07:44 UTC, merged