Feature/168 마이페이지 활동중인 모임 + 이전 자잘한 로직 수정
PLUB2022/Plub-Android pull request #47
Opened 2023-04-17 05:43 UTC by rudtjr1106

2023-04-17 07:30 UTC, jinukeu requested changes

2023-04-17 07:30 UTC, lluke0 commented on data/src/main/java/com/plub/data/mapper/myPageMapper/MyPageMyApplicationMapper.kt
> +                    position = plubbingInfo.address,
왜 position이 plubbingInfo.address야?

2023-04-17 07:30 UTC, lluke0 commented on domain/src/main/java/com/plub/domain/model/vo/myPage/MyPageDetailTitleVo.kt
> +    val position : String = "",
position이 string인 이유? 보통 정수타입 아닌가?

2023-04-17 07:30 UTC, lluke0 commented on domain/src/main/java/com/plub/domain/model/vo/signUp/hobbies/SignUpHobbiesVo.kt
> +) : SignUpPageVo, java.io.Serializable
import로 빼줘

2023-04-17 07:30 UTC, jinukeu commented on presentation/src/main/java/com/plub/presentation/ui/main/home/recruitment/apply/viewholder/QuestionsViewHolder.kt
> +            textViewNowText.text = editTextAnswer.text.length.toString()
이거 editText 변경할때마다 textViewNowText 값 실시간으로 변경돼?

2023-04-17 07:30 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/main/plubing/todo/adapter/TodoItemViewHolder.kt
> +            val checkRes = if(LocalDate.now().toString() == item.date) if(item.isChecked) R.drawable.ic_checked_12 else R.drawable.ic_unchecked_empty_c4c4c4
if문 조금 줄이기 가능? 예를 들면 when + if 조합으로 간다던가 ... ?

2023-04-17 07:30 UTC, jinukeu commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/MyPageViewModel.kt
> +        }
비동기로 호출하지 않은 이유?

2023-04-17 07:30 UTC, jinukeu commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/active/ActiveGatheringViewModel.kt
> +        viewModelScope.launch {
동기 호출을 한 이유?

2023-04-17 07:30 UTC, jinukeu commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/active/ActiveGatheringViewModel.kt
> +            if (index == MAX_SHOW_COUNT) {
.. 대신 until 쓰면 if문 빼버릴 수 있지 않아?

2023-04-17 07:30 UTC, jinukeu commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/active/ActiveGatheringViewModel.kt
> +            if (index == MAX_SHOW_COUNT) {
.. 대신 until 쓰면 if문 빼버릴 수 있지 않아?

2023-04-17 07:30 UTC, jinukeu commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/recruiting/viewHolder/MyPageDetailOtherApplicantsViewHolder.kt
> +            if(item.profileImage == null || item.profileImage == "") imageViewProfile.setImageResource(R.drawable.iv_default_profile)
isNullOrEmpty 있지 않음?

2023-04-17 07:30 UTC, jinukeu commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/recruiting/viewHolder/MyPageDetailOtherApplicantsViewHolder.kt
> +            else GlideUtil.loadImage(root.context, item.profileImage!!, imageViewProfile)
item.profileImage에는 null 값이 들어갈 수도 있지 않아?

2023-04-17 07:30 UTC, lluke0 commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/waiting/viewHolder/MyPageDetailMyApplicantsViewHolder.kt
> +            if(item.profileImage == null || item.profileImage == "") imageViewProfile.setImageResource(R.drawable.iv_default_profile)
isNullOrEmpty, 아래 else 문에서 profileImage는 null값이 될 수도 있음

2023-04-17 08:07 UTC, rudtjr1106 commented on data/src/main/java/com/plub/data/mapper/myPageMapper/MyPageMyApplicationMapper.kt
> +                    position = plubbingInfo.address,
네이밍이 position으로 해서 그런 것 같아 placeName으로 수정하겠습니당

2023-04-17 08:14 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/home/recruitment/apply/viewholder/QuestionsViewHolder.kt
> +            textViewNowText.text = editTextAnswer.text.length.toString()
네넹 실시간으로 변경됩니당

2023-04-17 08:21 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/plubing/todo/adapter/TodoItemViewHolder.kt
> +            val checkRes = if(LocalDate.now().toString() == item.date) if(item.isChecked) R.drawable.ic_checked_12 else R.drawable.ic_unchecked_empty_c4c4c4
함수화 시켜서 가독성이 좋게 변경했습니당

2023-04-17 08:27 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/MyPageViewModel.kt
> +        }
요거는 기획측 의도대로 순서가 바뀌면 안된다고 합니다 모집중인 모임 -> 대기중인 모임 -> 활동중인 모임 -> 종료된 모임
비동기로 처리할려면 그에 맞춰서 타입별로 순서를 다시 재정렬해주는 로직을 짜야 하는데 그것보다 요렇게 가는게 더 좋을 것 같아서 동기로 호출했습니당

2023-04-17 08:29 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/active/ActiveGatheringViewModel.kt
> +        viewModelScope.launch {
요거는 비동기로 처리 가능할 것 같아 로직 수정하겠습니다!

2023-04-17 08:30 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/recruiting/viewHolder/MyPageDetailOtherApplicantsViewHolder.kt
> +            else GlideUtil.loadImage(root.context, item.profileImage!!, imageViewProfile)
이미 앞에서 null 또는 empty값이 아님을 을 검사했기 때문에 non-null처리하여 두번 검증하는 일을 줄였습니다!

2023-04-18 00:44 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/active/ActiveGatheringViewModel.kt
> +        viewModelScope.launch {
처리 완료 했습니당

2023-04-18 00:56 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/MyPageViewModel.kt
> +        }
변경 -> 생각해보니 비동기로해도 로직이 어렵지 않아서 수정했습니당

2023-04-18 02:48 UTC, jinukeu approved these changes

2023-04-18 02:55 UTC, merged