Feature/184 notice
PLUB2022/Plub-Android pull request #48
Opened 2023-04-17 07:47 UTC by BehappyEveryone

공지작업

2023-04-17 08:17 UTC, jinukeu requested changes

2023-04-17 08:17 UTC, jinukeu commented on presentation/src/main/java/com/plub/presentation/ui/main/plubing/notice/NoticeFragment.kt
> +                    override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
확장 함수로 빼주면 좋을듯?

2023-04-17 08:17 UTC, jinukeu commented on presentation/src/main/java/com/plub/presentation/ui/main/plubing/notice/detail/NoticeDetailFragment.kt
> +                addOnScrollListener(object : RecyclerView.OnScrollListener() {
확장 함수 써주면 좋을듯

2023-04-25 07:20 UTC, rudtjr1106 approved these changes

2023-04-28 02:22 UTC, jinukeu approved these changes

2023-05-02 15:28 UTC, merged