Feature/177 report
PLUB2022/Plub-Android pull request #54
Opened 2023-05-03 06:33 UTC by rudtjr1106

2023-05-03 10:52 UTC, jinukeu requested changes

2023-05-03 10:52 UTC, jinukeu commented on presentation/src/main/java/com/plub/presentation/ui/main/report/detail/ReportDetailEvent.kt
> +    object BorderDefault : ReportDetailEvent()
BorderDefault 가 정확히 어떤 이벤트인지 감이 안와
좀 더 명확한 이름으로 바꿔줄 수 있을까?

2023-05-03 10:52 UTC, jinukeu commented on presentation/src/main/java/com/plub/presentation/ui/main/report/detail/ReportDetailViewModel.kt
> +        if(uiState.reportContent.value.isNotEmpty()) {
양방향 데이터 바인딩을 쓰지 않은 이유 궁금해

2023-05-04 07:11 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/report/detail/ReportDetailEvent.kt
> +    object BorderDefault : ReportDetailEvent()
BorderColorDefault 으로 변경했습니다!

2023-05-04 07:38 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/report/detail/ReportDetailViewModel.kt
> +        if(uiState.reportContent.value.isNotEmpty()) {
적용 완료했슴다!

2023-05-04 08:19 UTC, jinukeu approved these changes

2023-05-04 08:21 UTC, merged