Feature/203 profile page
PLUB2022/Plub-Android pull request #59
Opened 2023-05-26 01:59 UTC by rudtjr1106

2023-06-04 10:37 UTC, jinukeu requested changes

2023-06-04 10:37 UTC, jinukeu commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/MyPageViewModel.kt
> +                    profileImage = profileImage!!
!! 사용한 이유?

2023-06-05 01:04 UTC, rudtjr1106 commented on presentation/src/main/java/com/plub/presentation/ui/main/profile/MyPageViewModel.kt
> +                    profileImage = profileImage!!
저번에 profileImage 기본 이미지면 null로 내려온다 그래서 그에 맞게 대응했슴다
그래서 기본 이미지일 경우 해당 코드 위에 변수 profileImage를 NullOrEmpty로 빈 문자열값이 들어가도록 설정했으나 컴파일이 안되서 !!값을 추가했습니다 다만 위에서 이미 null일 경우를 판별했기 때문에 오류가 터질 위험은 없습니다!

2023-06-05 04:28 UTC, jinukeu approved these changes

2023-06-05 04:49 UTC, merged